_BASE_: "Base-BoxInst.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  RESNETS:
    DEPTH: 101
SOLVER:
  STEPS: (80000, 100000)
  MAX_ITER: 110000
OUTPUT_DIR: "output/boxinst_MS_R_101_1x"
