_BASE_: "Base-BoxInst.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/swin/swin_base_patch4_window7_224_22k.pth"
  BACKBONE:
    NAME: "build_fcos_swin_fpn_backbone"
  RESNETS:
    DEPTH: 101
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
OUTPUT_DIR: "output/boxinst_MS_R_101_3x"