_BASE_: "Base-BoxInst.yaml"
MODEL:
  WEIGHTS: "./swin_base_patch4_window7_224.pkl"
  RESNETS:
    OUT_FEATURES: ["p1", "p2", "p3"]
  FPN:
    IN_FEATURES: ["p1", "p2", "p3"]
  SWIN: True
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
OUTPUT_DIR: "output/boxinst_MS_R_101_3x"