_BASE_: "Base-BoxInst.yaml"
MODEL:
  WEIGHTS: "./swin_base_patch4_window12_384_22k.pkl"
  RESNETS:
    OUT_FEATURES: ["res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res3", "res4", "res5"]
  SWIN: True
  BOXINST:
    SEM_IN_CHANNELS: 256
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
OUTPUT_DIR: "output/boxinst_swin_B_3x"