_BASE_: "Base-BoxInst.yaml"
MODEL:
  WEIGHTS: "./swin_base_patch4_window7_224.pth"
  RESNETS:
    OUT_FEATURES: ["p1", "p2", "p3"]
  FPN:
    IN_FEATURES: ["p1", "p2", "p3"]
  SWIN: True
  BOXINST:
    SEM_IN_CHANNELS: 256
SOLVER:
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  BASE_LR: 0.0001
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True
OUTPUT_DIR: "output/boxinst_swin_B_1x"