_BASE_: "Base-BoxInst.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
DATASETS:
  TRAIN: ('voc_2012_train')
  TEST: ('voc_2012_val')
OUTPUT_DIR: "output/boxinst__VOC_MS_R_50_1x"