_BASE_: "Base-BoxInst.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  RESNETS:
    DEPTH: 101
  FCOS:
    NUM_CLASSES: 20
  BOXINST:
    ENABLED: True
    BOTTOM_PIXELS_REMOVED: 0
    PAIRWISE:
      WARMUP_ITERS: 1000
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('coco_2017_train',)
  TEST: ('coco_2017_val',)
SOLVER:
  IMS_PER_BATCH: 8
  STEPS: (12000, 16000)
  MAX_ITER: 18000
OUTPUT_DIR: "output/S2I_VOC_MS_R_101_1x"