FROM mirrors.tencent.com/star_library/g-tlinux2.2-python3.6-cuda11.0-cudnn8.1:latest

RUN pip3 install torch==1.10.1+cu113 torchvision==0.11.2+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html

RUN git clone https://github.com/facebookresearch/detectron2.git

ENV FORCE_CUDA="1"
ARG TORCH_CUDA_ARCH_LIST="Kepler;Kepler+Tesla;Maxwell;Maxwell+Tegra;Pascal;Volta;Turing"
ENV TORCH_CUDA_ARCH_LIST="${TORCH_CUDA_ARCH_LIST}"

RUN python3 -m pip install -e detectron2


COPY mask2former/modeling/pixel_decoder/ops /root/pixel_decoder/ops
WORKDIR /root/pixel_decoder/ops
RUN python3 setup.py build install

RUN pip3 install git+https://github.com/kornia/kornia

RUN pip3 install --no-cache-dir -e .

WORKDIR /home